# ASSIGNMENT 3

# QUESTION 1

In [1]:
import numpy as np

np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# QUESTION 2

In [2]:
import numpy as np
list1=[]
list2=[]
print("Enter elements of List1 : ")
for i in range(0,5):
    n = int(input())
    list1.append(n)
print("Enter elements of List2 : ")
for i in range(0,5):
    m = int(input())
    list2.append(m)
a1 = np.array(list1)
a2 = np.array(list2)

print("list1:",list1)
print("list2:",list2)
print("array1:",a1)
print("array2:",a2)

a3=np.array(np.concatenate((a1,a2)))
print("concatenated array:",a3)
print("sorted array1:")
print(np.sort(a1))
print("sorted array2:")
print(np.sort(a2))
print("sorted concatenated array:")
print(np.sort(a3))



Enter elements of List1 : 
9
3
1
7
4
Enter elements of List2 : 
10
2
8
5
6
list1: [9, 3, 1, 7, 4]
list2: [10, 2, 8, 5, 6]
array1: [9 3 1 7 4]
array2: [10  2  8  5  6]
concatenated array: [ 9  3  1  7  4 10  2  8  5  6]
sorted array1:
[1 3 4 7 9]
sorted array2:
[ 2  5  6  8 10]
sorted concatenated array:
[ 1  2  3  4  5  6  7  8  9 10]


# QUESTION 3

In [8]:
a=np.array([[1,  2,  3,  4],
            [5,  6,  7,  8],
            [9, 10, 11, 12]])
print(a)
print("DIMENTION : ",a.ndim,"\nSIZE : ",a.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
DIMENTION :  2 
SIZE :  12


# QUESTION 4

In [9]:
import numpy as np
array1=np.array([1,2,3,4])
print("1D ARRAY:",array1)
rearr=np.reshape(array1,(-1,2))
print("reshaped 2D:\n",rearr)

1D ARRAY: [1 2 3 4]
reshaped 2D:
 [[1 2]
 [3 4]]


In [10]:
import numpy as np
x = np.array([3,5,10,1,4])
y = x[:,np.newaxis]
print(y)

[[ 3]
 [ 5]
 [10]
 [ 1]
 [ 4]]


# QUESTION 5

In [11]:
import numpy as np
arr1=np.array([[0,1],[2,3]])
arr2=np.array([[4,5],[6,7]])
print("VERTICAL STACK: \n",np.vstack((arr1,arr2)))
print("HORIZONTAL STACK: \n",np.hstack((arr1,arr2)))

VERTICAL STACK: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
HORIZONTAL STACK: 
 [[0 1 4 5]
 [2 3 6 7]]


# QUESTION 6

In [13]:
a= np.array([0, 1, 2, 3, 1, 4, 5, 6,6])
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
np.count_nonzero(np.unique(a))

6